"""initial

Revision ID: 5eb5c632f36a
Revises: 
Create Date: 2023-08-01 10:09:27.581942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb5c632f36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('todos_user_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    op.drop_column('todos', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_user_id_fkey', 'todos', 'users', ['user_id'], ['id'])
    op.drop_column('todos', 'owner_id')
    # ### end Alembic commands ###
